import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Terms of Service | Roady',
  description: 'Terms of service for Roady, the AI-powered California road trip planner.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: '#ffffff', fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif" }}>
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 pt-32 pb-24">
        <h1 className="text-4xl font-extrabold mb-2" style={{ color: '#1B2D45' }}>Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-12">Last updated: April 15, 2025</p>

        <div className="prose prose-gray max-w-none" style={{ color: '#374151' }}>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>1. Acceptance of Terms</h2>
            <p className="leading-relaxed">By using Roady ("the Service"), you agree to these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>2. Description of Service</h2>
            <p className="leading-relaxed">Roady is a road trip planning tool that uses AI to generate personalized itineraries for California road trips. The Service is provided free of charge and is intended for personal, non-commercial use.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>3. AI-Generated Content</h2>
            <p className="leading-relaxed">Trip itineraries on Roady are generated by AI and are provided for informational purposes only. We do not guarantee the accuracy, completeness, or safety of any suggested routes, stops, or travel recommendations. Always verify information independently before traveling.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>4. User Accounts</h2>
            <p className="leading-relaxed mb-3">To save trips, you must sign in with a Google account. You are responsible for:</p>
            <ul className="list-disc pl-6 space-y-2 leading-relaxed">
              <li>Maintaining the security of your account.</li>
              <li>All activity that occurs under your account.</li>
              <li>Providing accurate information when using the Service.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>5. Prohibited Use</h2>
            <p className="leading-relaxed mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2 leading-relaxed">
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the Service.</li>
              <li>Use the Service to generate content for commercial redistribution without permission.</li>
            </ul>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>6. Disclaimer of Warranties</h2>
            <p className="leading-relaxed">The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that any generated trip content is accurate or safe to follow.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>7. Limitation of Liability</h2>
            <p className="leading-relaxed">To the fullest extent permitted by law, Roady shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service or reliance on AI-generated content.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>8. Changes to Terms</h2>
            <p className="leading-relaxed">We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-xl font-bold mb-3" style={{ color: '#1B2D45' }}>9. Contact</h2>
            <p className="leading-relaxed">For questions about these Terms, contact us at <a href="mailto:hismmotion@gmail.com" className="font-semibold" style={{ color: '#46a302' }}>hismmotion@gmail.com</a>.</p>
          </section>

        </div>
      </main>
    </div>
  );
}
