import type { PlannerRouteKey } from '@/components/home/plannerData';

export type WhereToGoTag = 'scenic-routes' | 'local-charm' | 'photo-worthy' | 'good-eats';

export type WhereToGoDestination = {
  id: string;
  name: string;
  slug: string;
  category: string;
  categoryColor: 'coral' | 'green' | 'gold' | 'purple';
  tags: WhereToGoTag[];
  region: string;
  description: string;
  image: string;
  stopCount: number;
  suggestedDays: number;
  fallbackRouteId: PlannerRouteKey;
};

export const WHERE_TO_GO_TAGS: Array<{
  id: WhereToGoTag;
  label: string;
  description: string;
  color: string;
  bg: string;
}> = [
  {
    id: 'scenic-routes',
    label: 'Scenic routes',
    description: 'Breathtaking drives and viewpoints',
    color: '#D85A30',
    bg: '#FFF0E9',
  },
  {
    id: 'local-charm',
    label: 'Local charm',
    description: 'Unique towns with local character',
    color: '#D8941F',
    bg: '#FFF7DF',
  },
  {
    id: 'photo-worthy',
    label: 'Photo worthy',
    description: "Spots you'll want to remember",
    color: '#1D9E75',
    bg: '#EFFFF4',
  },
  {
    id: 'good-eats',
    label: 'Good eats',
    description: 'Local flavors along the way',
    color: '#6F4BC7',
    bg: '#F1ECFF',
  },
];

export const WHERE_TO_GO_DESTINATIONS: WhereToGoDestination[] = [
  {
    id: 'big-sur',
    name: 'Big Sur',
    slug: 'big-sur',
    category: 'Scenic Drive',
    categoryColor: 'coral',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Central Coast',
    description: 'Dramatic coastline, redwoods, cliffside pullouts, and iconic Pacific views.',
    image: 'https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?w=900&q=85',
    stopCount: 12,
    suggestedDays: 4,
    fallbackRouteId: 'pch',
  },
  {
    id: 'solvang',
    name: 'Solvang',
    slug: 'solvang',
    category: 'Small Town',
    categoryColor: 'gold',
    tags: ['local-charm', 'good-eats', 'photo-worthy'],
    region: 'Santa Ynez Valley',
    description: 'A Danish-inspired town with bakeries, boutiques, wine stops, and relaxed valley roads.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=85',
    stopCount: 8,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'joshua-tree',
    name: 'Joshua Tree',
    slug: 'joshua-tree',
    category: 'Desert Escape',
    categoryColor: 'green',
    tags: ['photo-worthy', 'scenic-routes'],
    region: 'Inland Empire',
    description: 'Otherworldly boulders, desert art, golden light, and starry skies.',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'desert',
  },
  {
    id: 'cambria',
    name: 'Cambria',
    slug: 'cambria',
    category: 'Coastal Town',
    categoryColor: 'purple',
    tags: ['local-charm', 'scenic-routes', 'good-eats'],
    region: 'Central Coast',
    description: 'Art galleries, ocean views, quiet beaches, and a laid-back coastal village feel.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'yosemite',
    name: 'Yosemite National Park',
    slug: 'yosemite',
    category: 'Outdoor Adventure',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Sierra Nevada',
    description: 'Granite walls, waterfalls, meadows, and classic California mountain drama.',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=900&q=85',
    stopCount: 9,
    suggestedDays: 4,
    fallbackRouteId: 'parks',
  },
  {
    id: 'palm-springs',
    name: 'Palm Springs',
    slug: 'palm-springs',
    category: 'Desert Escape',
    categoryColor: 'purple',
    tags: ['photo-worthy', 'good-eats', 'local-charm'],
    region: 'Coachella Valley',
    description: 'Retro architecture, mountain backdrops, pool-town energy, and easy desert detours.',
    image: 'https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'desert',
  },
  {
    id: 'paso-robles',
    name: 'Paso Robles',
    slug: 'paso-robles',
    category: 'Wine Country',
    categoryColor: 'coral',
    tags: ['good-eats', 'local-charm', 'scenic-routes'],
    region: 'Central Coast',
    description: 'Rolling vineyards, warm downtown evenings, mineral springs, and slow country roads.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'lake-tahoe',
    name: 'Lake Tahoe',
    slug: 'lake-tahoe',
    category: 'Mountain Lake',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy', 'local-charm'],
    region: 'Sierra Nevada',
    description: 'Clear blue water, alpine viewpoints, mountain towns, and year-round outdoor stops.',
    image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=900&q=85',
    stopCount: 10,
    suggestedDays: 4,
    fallbackRouteId: 'custom',
  },
  {
    id: 'santa-barbara',
    name: 'Santa Barbara',
    slug: 'santa-barbara',
    category: 'Coastal Town',
    categoryColor: 'purple',
    tags: ['local-charm', 'good-eats', 'photo-worthy'],
    region: 'Central Coast',
    description: 'Spanish-style streets, beach walks, courthouse views, and easy sunset dining.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 8,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'monterey',
    name: 'Monterey',
    slug: 'monterey',
    category: 'Coastal Town',
    categoryColor: 'coral',
    tags: ['scenic-routes', 'good-eats', 'photo-worthy'],
    region: 'Monterey Bay',
    description: 'Bayfront paths, sea life, seafood stops, and quick access to Pacific Grove and Carmel.',
    image: 'https://images.unsplash.com/photo-1590523278191-995cbcda646b?w=900&q=85',
    stopCount: 9,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'mendocino',
    name: 'Mendocino',
    slug: 'mendocino',
    category: 'Cliffside Village',
    categoryColor: 'green',
    tags: ['scenic-routes', 'local-charm', 'photo-worthy'],
    region: 'North Coast',
    description: 'Windy bluffs, Victorian charm, forest detours, and a slower northern coast mood.',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=900&q=85',
    stopCount: 7,
    suggestedDays: 4,
    fallbackRouteId: 'pch',
  },
  {
    id: 'ojai',
    name: 'Ojai',
    slug: 'ojai',
    category: 'Valley Escape',
    categoryColor: 'gold',
    tags: ['local-charm', 'good-eats', 'photo-worthy'],
    region: 'Ventura County',
    description: 'Orange groves, indie shops, mountain views, and a mellow valley reset.',
    image: 'https://images.unsplash.com/photo-1560493676-04071c5f467b?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'custom',
  },
  {
    id: 'mammoth-lakes',
    name: 'Mammoth Lakes',
    slug: 'mammoth-lakes',
    category: 'Mountain Escape',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Eastern Sierra',
    description: 'Alpine lakes, hot springs, huge Sierra views, and a dramatic Highway 395 approach.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=85',
    stopCount: 10,
    suggestedDays: 4,
    fallbackRouteId: 'parks',
  },
  {
    id: 'carmel-by-the-sea',
    name: 'Carmel-by-the-Sea',
    slug: 'carmel-by-the-sea',
    category: 'Coastal Village',
    categoryColor: 'gold',
    tags: ['local-charm', 'photo-worthy', 'good-eats'],
    region: 'Monterey Bay',
    description: 'Storybook cottages, white-sand beach walks, galleries, cafes, and easy 17-Mile Drive detours.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'point-reyes',
    name: 'Point Reyes',
    slug: 'point-reyes',
    category: 'Coastal Preserve',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy', 'local-charm'],
    region: 'Marin County',
    description: 'Wild beaches, windswept headlands, dairy-country roads, and quiet oyster-town stops.',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=900&q=85',
    stopCount: 8,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'san-luis-obispo',
    name: 'San Luis Obispo',
    slug: 'san-luis-obispo',
    category: 'College Town',
    categoryColor: 'purple',
    tags: ['good-eats', 'local-charm', 'scenic-routes'],
    region: 'Central Coast',
    description: 'Mission plaza strolls, farm-to-table food, nearby beaches, and easy wine-country side trips.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'death-valley',
    name: 'Death Valley',
    slug: 'death-valley',
    category: 'Desert Wonder',
    categoryColor: 'coral',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Mojave Desert',
    description: 'Salt flats, painted badlands, huge desert horizons, and some of California’s most surreal drives.',
    image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=900&q=85',
    stopCount: 9,
    suggestedDays: 4,
    fallbackRouteId: 'desert',
  },
  {
    id: 'sequoia-kings-canyon',
    name: 'Sequoia & Kings Canyon',
    slug: 'sequoia-kings-canyon',
    category: 'National Parks',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Sierra Nevada',
    description: 'Giant sequoias, canyon viewpoints, forest roads, and cool mountain air.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85',
    stopCount: 10,
    suggestedDays: 4,
    fallbackRouteId: 'parks',
  },
  {
    id: 'idyllwild',
    name: 'Idyllwild',
    slug: 'idyllwild',
    category: 'Mountain Town',
    categoryColor: 'gold',
    tags: ['local-charm', 'photo-worthy', 'good-eats'],
    region: 'San Jacinto Mountains',
    description: 'Pine forest cabins, indie shops, trailheads, mountain cafes, and a cozy small-town feel.',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'desert',
  },
  {
    id: 'napa-valley',
    name: 'Napa Valley',
    slug: 'napa-valley',
    category: 'Wine Country',
    categoryColor: 'coral',
    tags: ['good-eats', 'scenic-routes', 'local-charm'],
    region: 'North Bay',
    description: 'Vineyard roads, relaxed towns, destination restaurants, and scenic valley viewpoints.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'san-diego-coast',
    name: 'San Diego Coast',
    slug: 'san-diego-coast',
    category: 'Beach Cities',
    categoryColor: 'purple',
    tags: ['good-eats', 'photo-worthy', 'scenic-routes'],
    region: 'Southern California',
    description: 'Surf towns, taco stops, ocean overlooks, beach walks, and sunny coastal neighborhoods.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 8,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'healdsburg',
    name: 'Healdsburg',
    slug: 'healdsburg',
    category: 'Wine Country',
    categoryColor: 'coral',
    tags: ['good-eats', 'local-charm', 'scenic-routes'],
    region: 'Sonoma County',
    description: 'Vineyard loops, river roads, relaxed tasting rooms, and a polished small-town food scene.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'half-moon-bay',
    name: 'Half Moon Bay',
    slug: 'half-moon-bay',
    category: 'Coastal Town',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy', 'good-eats'],
    region: 'Peninsula Coast',
    description: 'Bluff trails, harbor seafood, wide beaches, and quiet Highway 1 viewpoints.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
  {
    id: 'laguna-beach',
    name: 'Laguna Beach',
    slug: 'laguna-beach',
    category: 'Art Coast',
    categoryColor: 'gold',
    tags: ['photo-worthy', 'local-charm', 'good-eats'],
    region: 'Orange County',
    description: 'Cove beaches, gallery walks, coastal restaurants, and dramatic ocean overlook stops.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'santa-cruz',
    name: 'Santa Cruz',
    slug: 'santa-cruz',
    category: 'Surf Town',
    categoryColor: 'purple',
    tags: ['good-eats', 'local-charm', 'photo-worthy'],
    region: 'Monterey Bay',
    description: 'Surf breaks, redwood detours, boardwalk energy, beach cafes, and laid-back coastal drives.',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'mount-shasta',
    name: 'Mount Shasta',
    slug: 'mount-shasta',
    category: 'Mountain Escape',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Northern California',
    description: 'Snowy peak views, alpine lakes, waterfalls, forest roads, and quiet mountain-town stops.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=85',
    stopCount: 8,
    suggestedDays: 4,
    fallbackRouteId: 'parks',
  },
  {
    id: 'lassen-volcanic',
    name: 'Lassen Volcanic',
    slug: 'lassen-volcanic',
    category: 'Volcanic Park',
    categoryColor: 'coral',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Cascade Range',
    description: 'Steam vents, mountain lakes, volcanic landscapes, and a quieter national park loop.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85',
    stopCount: 8,
    suggestedDays: 3,
    fallbackRouteId: 'parks',
  },
  {
    id: 'borrego-springs',
    name: 'Borrego Springs',
    slug: 'borrego-springs',
    category: 'Desert Town',
    categoryColor: 'gold',
    tags: ['photo-worthy', 'scenic-routes', 'local-charm'],
    region: 'Anza-Borrego Desert',
    description: 'Desert sculptures, palm canyons, starry skies, and open roads through rugged badlands.',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'desert',
  },
  {
    id: 'malibu',
    name: 'Malibu',
    slug: 'malibu',
    category: 'Coastal Drive',
    categoryColor: 'purple',
    tags: ['scenic-routes', 'photo-worthy', 'good-eats'],
    region: 'Los Angeles County',
    description: 'Canyon roads, beach overlooks, oceanfront food stops, and classic Pacific Coast Highway views.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 6,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
  {
    id: 'avila-beach',
    name: 'Avila Beach',
    slug: 'avila-beach',
    category: 'Beach Town',
    categoryColor: 'green',
    tags: ['local-charm', 'good-eats', 'photo-worthy'],
    region: 'Central Coast',
    description: 'Sunny coves, pier walks, hot springs nearby, seafood stops, and mellow coastal scenery.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
  {
    id: 'julian',
    name: 'Julian',
    slug: 'julian',
    category: 'Mountain Town',
    categoryColor: 'coral',
    tags: ['local-charm', 'good-eats', 'scenic-routes'],
    region: 'San Diego County',
    description: 'Apple pie stops, piney mountain roads, historic storefronts, and easy desert side trips.',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'desert',
  },
  {
    id: 'russian-river',
    name: 'Russian River',
    slug: 'russian-river',
    category: 'River Escape',
    categoryColor: 'green',
    tags: ['local-charm', 'scenic-routes', 'good-eats'],
    region: 'Sonoma County',
    description: 'Redwood-lined roads, river beaches, relaxed towns, and easy detours toward the coast.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'custom',
  },
  {
    id: 'pismo-beach',
    name: 'Pismo Beach',
    slug: 'pismo-beach',
    category: 'Beach Town',
    categoryColor: 'gold',
    tags: ['photo-worthy', 'good-eats', 'local-charm'],
    region: 'Central Coast',
    description: 'Wide sand, pier walks, clam chowder stops, dunes, and a breezy Central Coast pace.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
  {
    id: 'redwood-parks',
    name: 'Redwood Parks',
    slug: 'redwood-parks',
    category: 'Forest Drive',
    categoryColor: 'green',
    tags: ['scenic-routes', 'photo-worthy'],
    region: 'Far North Coast',
    description: 'Old-growth groves, misty coastal roads, fern canyons, and quiet forest pullouts.',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=900&q=85',
    stopCount: 9,
    suggestedDays: 4,
    fallbackRouteId: 'parks',
  },
  {
    id: 'trinidad',
    name: 'Trinidad',
    slug: 'trinidad',
    category: 'Coastal Village',
    categoryColor: 'purple',
    tags: ['photo-worthy', 'scenic-routes', 'local-charm'],
    region: 'Humboldt Coast',
    description: 'Sea stacks, harbor views, redwood access, hidden beaches, and a tiny coastal-town feel.',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'pch',
  },
  {
    id: 'bishop',
    name: 'Bishop',
    slug: 'bishop',
    category: 'Eastern Sierra',
    categoryColor: 'coral',
    tags: ['scenic-routes', 'good-eats', 'photo-worthy'],
    region: 'Owens Valley',
    description: 'Bakery stops, boulder fields, alpine lake roads, and big Sierra-to-desert views.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=85',
    stopCount: 7,
    suggestedDays: 3,
    fallbackRouteId: 'parks',
  },
  {
    id: 'lone-pine',
    name: 'Lone Pine',
    slug: 'lone-pine',
    category: 'Desert Gateway',
    categoryColor: 'gold',
    tags: ['photo-worthy', 'scenic-routes', 'local-charm'],
    region: 'Eastern Sierra',
    description: 'Alabama Hills arches, Mount Whitney views, desert roads, and classic Highway 395 scenery.',
    image: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=900&q=85',
    stopCount: 6,
    suggestedDays: 3,
    fallbackRouteId: 'desert',
  },
  {
    id: 'temecula',
    name: 'Temecula',
    slug: 'temecula',
    category: 'Wine Country',
    categoryColor: 'coral',
    tags: ['good-eats', 'local-charm', 'scenic-routes'],
    region: 'Inland Southern California',
    description: 'Rolling vineyard roads, Old Town patios, hot air balloon views, and easy weekend pacing.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=900&q=85',
    stopCount: 6,
    suggestedDays: 2,
    fallbackRouteId: 'custom',
  },
  {
    id: 'catalina-island',
    name: 'Catalina Island',
    slug: 'catalina-island',
    category: 'Island Escape',
    categoryColor: 'purple',
    tags: ['photo-worthy', 'local-charm', 'good-eats'],
    region: 'Southern California Coast',
    description: 'Avalon harbor views, island walks, golf cart cruising, seafood stops, and clear blue coves.',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
  {
    id: 'los-olivos',
    name: 'Los Olivos',
    slug: 'los-olivos',
    category: 'Wine Village',
    categoryColor: 'gold',
    tags: ['good-eats', 'local-charm', 'scenic-routes'],
    region: 'Santa Ynez Valley',
    description: 'Tasting rooms, ranch roads, boutique shops, and sunny valley drives near Santa Barbara.',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'custom',
  },
  {
    id: 'sausalito',
    name: 'Sausalito',
    slug: 'sausalito',
    category: 'Bay Escape',
    categoryColor: 'green',
    tags: ['photo-worthy', 'good-eats', 'local-charm'],
    region: 'Marin County',
    description: 'Waterfront views, hillside lanes, ferry rides, cafes, and quick access to Marin headlands.',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=900&q=85',
    stopCount: 5,
    suggestedDays: 2,
    fallbackRouteId: 'pch',
  },
];

export function getWhereToGoDestination(slug: string | null) {
  if (!slug) return null;
  return WHERE_TO_GO_DESTINATIONS.find((destination) => destination.slug === slug) ?? null;
}
